### ISSUE TITLE
sap_install_media_detect: regression after PR #522

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#526]
There is no field named `file` in the loop variables of task `SAP Install Media Detect - Organize all files - Create SWPM target directories` of `roles/sap_install_media_detect/tasks/organize_files.yml`. This causes the task to fail with:
`Failed to template loop_control.label: 'str object' has no attribute 'file'. 'str object' has no attribute 'file'`.

**Comment by berndfinger** [comment]
Solved in #527 .
